-- Add device registration fields to student_profiles
ALTER TABLE student_profiles
  ADD COLUMN IF NOT EXISTS registered_device_id   text NULL,
  ADD COLUMN IF NOT EXISTS registered_device_info jsonb NULL;

-- Index for fast lookup during every student login
CREATE INDEX IF NOT EXISTS idx_student_profiles_registered_device
  ON student_profiles(registered_device_id)
  WHERE registered_device_id IS NOT NULL;

COMMENT ON COLUMN student_profiles.registered_device_id IS
  'UUID generated by the client browser (localStorage: aviora_device_id). '
  'Set on first student login. NULL means device not yet registered or cleared by admin.';

COMMENT ON COLUMN student_profiles.registered_device_info IS
  'Supplementary device info stored at registration time. '
  'Example: {"user_agent": "...", "ip_address": "...", "screen_width": 1280, '
  '"registered_at": "2024-01-15T10:00:00Z", "last_login_at": "2024-01-20T14:00:00Z"}';
